# Solving Linear Equations

The basic example of solving linear equations

Solve linear equations
3x - 9y = - 42,
2x + 4y = 2

In [3]:
import numpy as np

In [4]:
A = np.array([[3,-9],[2,4]])
A

array([[ 3, -9],
       [ 2,  4]])

In [5]:
b = np.array([-42,2])
b

array([-42,   2])

In [6]:
z = np.linalg.solve(A,b)
z

array([-5.,  3.])

Problem2:

x - 2y - z = 6,
2x + 2y - z =1,
-x - y+ 2z =1

In [7]:
C = np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])
C

array([[ 1, -2, -1],
       [ 2,  2, -1],
       [-1, -1,  2]])

In [8]:
D =  np.array([6,1,1])
D

array([6, 1, 1])

In [9]:
z1 = np.linalg.solve(C,D)
z1

array([ 3., -2.,  1.])